### ISSUE TITLE
Add Copy Editor plugin

### ISSUE THREAD

**Issue by mattbond21** [buzzfeed/Sketch-Toolbox#51]
https://github.com/zakkain/sketch-copyeditor

**Comment by florianbuerger** [comment]
Please edit the `plugins.json` in `src/data` and open a pull request. Thanks.

**Comment by mattbond21** [comment]
Searching the repo doesn't show a plugins.json file at all. I also can't
see this comment on GitHub, perhaps this comment was for a separate
issue/repo?

**Comment by florianbuerger** [comment]
Yes, you're right, my mind was in a different repository. Sorry about that.

**Comment by bomberstudios** [comment]
FTR, the plugin was added to the plugin-directory repo yesterday, so this issue can be closed
